openapi: 3.0.0
info:
    title: hello-api service
    description: инициализация сервиса
    version: 0.0.1
servers:
    - url: http://localhost:9000
paths:
    /hello/hello:
        post:
            tags:
                - Hello
            description: возвращает hello world
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    example: 1
                                    oneOf:
                                        - type: number
                                        - type: string
                                          format: uuid
                                jsonrpc:
                                    type: string
                                    example: "2.0"
                                params:
                                    $ref: '#/components/schemas/requestHelloHello'
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                oneOf:
                                    - type: object
                                      properties:
                                        id:
                                            example: 1
                                            oneOf:
                                                - type: number
                                                - type: string
                                                  format: uuid
                                        jsonrpc:
                                            type: string
                                            example: "2.0"
                                        result:
                                            $ref: '#/components/schemas/responseHelloHello'
                                    - type: object
                                      properties:
                                        error:
                                            type: object
                                            properties:
                                                code:
                                                    type: number
                                                    format: int32
                                                    example: -32603
                                                data:
                                                    type: object
                                                    nullable: true
                                                message:
                                                    type: string
                                                    example: not found
                                            nullable: true
                                        id:
                                            example: 1
                                            oneOf:
                                                - type: number
                                                - type: string
                                                  format: uuid
                                        jsonrpc:
                                            type: string
                                            example: "2.0"
components:
    schemas:
        requestHelloHello:
            type: object
            properties:
                name:
                    type: string
            description: возвращает hello world
        responseHelloHello:
            type: object
            properties:
                resp:
                    type: string
            description: возвращает hello world
