// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/KatharsisTL/transport-generator-example/internal/api/service"
)

type HelloHello func(ctx context.Context, name string) (resp string, err error)

type MiddlewareHello func(next service.Hello) service.Hello

type MiddlewareHelloHello func(next HelloHello) HelloHello
